version: '3.7'
services:
  proxy:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - '443:443'
    extra_hosts:
      - "${NGINX_PROXY_HOST}:${NGINX_PROXY_IP}"      
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./log:/var/log/nginx
      - ./config:/etc/nginx/conf.d