version: '3.7'
services:
  agent:
    init: true
    container_name: ethstats
    image: xdaichain/ethstats-agent:latest
    links:
      - "node"
    depends_on:
      - "node"
    environment:
      NODE_ENV: production
      RPC_HOST: node
      RPC_PORT: 8545
      LISTENING_PORT: 30303
      CONTACT_DETAILS: "https://t.me/PolisPayOfficial"
      INSTANCE_NAME: ${ETHSTATS_ID}
      WS_SERVER: "wss://sparta-stats.polis.tech/api"
      WS_SECRET: "PhD8zsx69jhpqv7PUhzz2mExj66hT8tRknP7Rw7sCC5y79SAgQuZLW6cXUuqjRnv"
      VERBOSITY: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  node:
    init: true
    container_name: node
    image: ghcr.io/polischain/openethereum:main
    user: root
    command:
      --chain=sparta
      --base-path=/root/data
      --engine-signer="0x276f658ddbfd910e27800ea0232e733e138ac478"
      --unlock="0x276f658ddbfd910e27800ea0232e733e138ac478"
      --password="/root/password/0x276f658ddbfd910e27800ea0232e733e138ac478"
      --pruning=archive
      --max-peers="100"
      --jsonrpc-port="8545"
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --fat-db="on"
      --tracing="on"
      --ws-port="8546"
      --ws-interface all
      --ws-apis=all
      --ws-origins all
      --ws-hosts all
      --logging="info,rpc=debug"
    volumes:
      - ./node_data:/root/data
      - ./passwords:/root/password
      - ./keys:/root/data/keys/sparta
    ports:
      - "8546:8546"
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always