version: '3.7'
services:
  node:
    init: true
    container_name: node
    image: ghcr.io/polischain/openethereum:main
    user: root
    command:
      --chain=sparta
      --base-path=/root/data
      --max-peers=100
      --jsonrpc-interface all
      --jsonrpc-apis web3,eth,net,parity,pubsub,traces
      --ws-interface local
      --fat-db=on
      --pruning=archive
      --ws-apis all
      --ws-origins all
      --ws-hosts all
      --ws-port 8546
    volumes:
      - ./node_data:/root/data
    ports:
      - '30303:30303/udp'
      - '30303:30303'
      - '127.0.0.1:8545:8545'
      - '127.0.0.1:8546:8546'
    restart: always