version: '3.7'
services:
  node:
    image: ghcr.io/polischain/polis-chains:main
    volumes:
      - ./db/:/nethermind/nethermind_db/
      - ./logs/:/nethermind/logs/
    ports:
      - '30303:30303/udp'
      - '30303:30303'
      - '8545:8545'
      - '8546:8546'
    environment:
      NETHERMIND_CONFIG: "sparta"
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_WEBSOCKETSPORT: "8546"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SECRET: "PhD8zsx69jhpqv7PUhzz2mExj66hT8tRknP7Rw7sCC5y79SAgQuZLW6cXUuqjRnv"
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://sparta-stats.polis.tech/api"
      NETHERMIND_ETHSTATSCONFIG_NAME: "Blockscout Node"
      NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES: "eth,subscribe,trace,txpool,web3,proof,net,parity,health"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: "0.0.0.0"
  blockscout:
    image: ghcr.io/polischain/blockscout:master
    ports:
      - '4000:4000'
    depends_on:
      - node
      - postgres
    environment:
      DATABASE_URL: "postgresql://blockscout:let-me-in@host.docker.internal:5432/blockscout?ssl=false"
      COIN: "polis"
      NETWORK: "Polis"
      SUBNETWORK: "Sparta"
      LOGO: "/images/polis_logo.svg"
      ETHEREUM_JSONRPC_VARIANT: "parity"
      ETHEREUM_JSONRPC_HTTP_URL: "http://host.docker.internal:8545"
      ETHEREUM_JSONRPC_TRACE_URL: "http://host.docker.internal:8545"
      ETHEREUM_JSONRPC_WS_URL: "ws://host.docker.internal:8546"
      SECRET_KEY_BASE: "RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5"
      PORT: "4000"
      MIX_ENV: "prod"
      CHAIN_ID: "333888"
      CHAIN_SPEC_PATH: "https://raw.githubusercontent.com/polischain/polis-chains/main/specs/sparta.json"
      LINK_TO_OTHER_EXPLORER: "false"
      SHOW_PRICE_CHART: "false"
      SHOW_TXS_CHART: "true"
      ENABLE_TXS_STATS: "true"
      ENABLE_POS_STAKING_IN_MENU: "true"
      POS_STAKING_CONTRACT: "0x9eB738D4678B276F5d6B5043849502B683d2cC93"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "mix phx.server"
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: blockscout
    volumes:
      - ./data/postgres:/var/lib/postgresql/data