version: '3.7'
services:
  blockscout:
    image: ghcr.io/polischain/blockscout:master
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://blockscout:let-me-in@host.docker.internal:5432/blockscout?ssl=false"
      COIN: "polis"
      NETWORK: "Polis"
      SUBNETWORK: "Olympus"
      LOGO: "/images/polis_logo.svg"
      BLOCKSCOUT_HOST: "explorer.polis.tech"
      COINGECKO_COIN_ID: "polis"
      VALIDATORS_CONTRACT: "0x636278bAd2D76AAC5E9bAcfd185687c8901063E9"
      TOKEN_BRIDGE_CONTRACT: "0x8B95D92bea3e67796A105c19c524Ee8ef87Bd537"
      HIDE_BLOCK_MINER: "false"
      DISPLAY_TOKEN_ICONS: "true"
      BLOCKSCOUT_PROTOCOL: "https"
      ETHEREUM_JSONRPC_VARIANT: "parity"
      ETHEREUM_JSONRPC_HTTP_URL: "https://rpc-tracing.polis.tech"
      ETHEREUM_JSONRPC_TRACE_URL: "https://rpc-tracing.polis.tech"
      SECRET_KEY_BASE: "RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5"
      PORT: "4000"
      MIX_ENV: "prod"
      CHAIN_ID: "333999"
      CHAIN_SPEC_PATH: "https://raw.githubusercontent.com/polischain/polis-chains/main/specs/olympus.json"
      LINK_TO_OTHER_EXPLORER: "false"
      SHOW_PRICE_CHART: "true"
      SHOW_TXS_CHART: "true"
      ENABLE_TXS_STATS: "true"
      ENABLE_POS_STAKING_IN_MENU: "true"
      GAS_PRICE: "1"
      POS_STAKING_CONTRACT: "0xF69e9147d88De50c4Bd42F9b41Cbce00841Cc2Dd"
    command: bash -c "mix do ecto.migrate && mix phx.server"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: blockscout
    volumes:
      - ./data/postgres:/var/lib/postgresql/data