version: '3.7'
services:
  agent:
    init: true
    container_name: ethstats
    image: xdaichain/ethstats-agent:latest
    links:
      - "node"
    depends_on:
      - "node"
    environment:
      NODE_ENV: production
      RPC_HOST: ${IP}
      RPC_PORT: 8545
      LISTENING_PORT: 30303
      CONTACT_DETAILS: "https://t.me/PolisPayOfficial"
      INSTANCE_NAME: ${ETHSTATS_ID}
      WS_SERVER: "wss://dev-netstats.polis.tech/api"
      WS_SECRET: ${ETHSTATS_KEY}
      VERBOSITY: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  node:
    init: true
    container_name: node
    image: ghcr.io/polischain/openethereum:main
    user: root
    command:
      --chain=olympus
      --base-path=/root/data
      --pruning=archive
      --max-peers="100"
      --min-gas-price="1000000000"
      --force-sealing
      --fast-unlock
      --jsonrpc-port="8545"
      --jsonrpc-cors=all
      --gas-floor-target="20000000"
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --fat-db="on"
      --tracing="on"
      --ws-port="8546"
      --ws-interface all
      --ws-apis=all
      --ws-origins all
      --ws-hosts all
      --logging="rpc=warn"
      --metrics
      --metrics-port=6060
    healthcheck:
      test: [ "CMD", "sh", "-c", "(curl -sf --connect-timeout 1 --max-time 2 --retry 2 --retry-delay 3 --retry-max-time 15 http://localhost:6060/metrics >/dev/null && curl -sf --connect-timeout 1 --max-time 2 --retry 2 --retry-delay 3 --retry-max-time 15 -X POST -H 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_chainId\",\"id\":1}' http://localhost:8545/ >/dev/null) || sh -c 'pkill -15 openethereum && (sleep 10; pkill -9 openethereum) ; return 1'" ]
      interval: 60s
      timeout: 30s
      start_period: 60s
    volumes:
      - ./node_data:/root/data
    ports:
      - "${IP}:8546:8546"
      - "${IP}:8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always