version: '3.7'
services:
  node:
    init: true
    container_name: node
    image: ghcr.io/polischain/polis-chains:main
    user: root
    volumes:
      - ./node_data/db:/nethermind/nethermind_db/
      - ./node_data/keystore/:/nethermind/keystore
    environment:
      NETHERMIND_CONFIG: "olympus"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SECRET: ${ETHSTATS_KEY}
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://dev-netstats.polis.tech/api"
      NETHERMIND_ETHSTATSCONFIG_NAME: ${ETHSTATS_ID}
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "false"
      NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES: "eth,subscribe,txpool,web3,proof,net,parity,health"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: "0.0.0.0"
    ports:
      - "${IP}:8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always