version: '3.7'
services:
  agent:
    init: true
    container_name: ethstats
    image: xdaichain/ethstats-agent:latest
    links:
      - "node"
    depends_on:
      - "node"
    environment:
      NODE_ENV: production
      RPC_HOST: ${IP}
      RPC_PORT: 8545
      LISTENING_PORT: 30303
      CONTACT_DETAILS: "https://t.me/PolisPayOfficial"
      INSTANCE_NAME: ${ETHSTATS_ID}
      WS_SERVER: "wss://netstats.dev.polis.tech/api"
      WS_SECRET: ${ETHSTATS_KEY}"
      VERBOSITY: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  node:
    init: true
    container_name: node
    image: ghcr.io/polischain/openethereum:main
    user: root
    command:
      --chain=sparta
      --base-path=/root/data
      --pruning=archive
      --max-peers=100
      --tx-time-limit=1000
      --jsonrpc-port=8545
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=web3,eth,net,parity,traces
      --fat-db="on"
      --tracing="on"
    volumes:
      - ./node_data:/root/data
    ports:
      - "${IP}:8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    restart: always