version: '3.7'
services:
  validator:
    init: true
    container_name: validator
    image: ghcr.io/polischain/polis-chains:main
    user: root
    volumes:
      - ~/polis-chains/passwords/:/nethermind/passwords
      - ~/polis-chains/db/:/nethermind/nethermind_db
      - ~/polis-chains/keystore/:/nethermind/keystore
      - ~/polis-chains/logs/:/nethermind/logs/
    environment:
      NETHERMIND_CONFIG: "olympus_validator"
      NETHERMIND_AURACONFIG_FORCESEALING: "true"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SECRET: "EfxqGbcCZnxBPNgqb2UcWqgJK49VnKZv"
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://netstats.polis.tech/api"
      NETHERMIND_ETHSTATSCONFIG_NAME: $NAME
      NETHERMIND_INITCONFIG_ISMINING: "true"
      NETHERMIND_MININGCONFIG_ENABLED: "true"
      NETHERMIND_INITCONFIG_STORERECEIPTS: "false"
      NETHERMIND_MININGCONFIG_MINGASPRICE: "1000000000"
      NETHERMIND_MININGCONFIG_TARGETBLOCKGASLIMIT: "20000000"
      NETHERMIND_PRUNINGCONFIG_ENABLED: "false"
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_SYNCCONFIG_FASTBLOCKS: "true"
      NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC: "false"
      NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC: "false"
      NETHERMIND_KEYSTORECONFIG_BLOCKAUTHORACCOUNT: $ACCOUNT
      NETHERMIND_KEYSTORECONFIG_UNLOCKACCOUNTS: "$ACCOUNT"
      NETHERMIND_KEYSTORECONFIG_PASSWORDFILES: /nethermind/passwords/$ACCOUNT
      NETHERMIND_HEALTHCHECKSCONFIG_ENABLED: "true"
      NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED: "true"
      NETHERMIND_HEALTHCHECKSCONFIG_MAXINTERVALWITHOUTPROCESSEDBLOCK: 100
      NETHERMIND_HEALTHCHECKSCONFIG_MAXINTERVALWITHOUTPRODUCEDBLOCK: 100
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    restart: always