version: '3.7'
services:
  node:
    init: true
    container_name: node
    image: ghcr.io/finachain/openethereum:main
    user: root
    command:
      --chain=finachain
      --base-path=/root/data
      --pruning=archive
      --max-peers="500"
      --no-jsonrpc
      --fat-db="off"
      --tracing="off"
      --no-ws   
      --logging="engine=info,miner=info,rpc=info"
    volumes:
      - ./node_data:/root/data
    ports:
      - "40101:40101"
      - "40101:40101/udp"
    restart: always