version: '3.7'
services:
  agent:
    init: true
    container_name: ethstats-agent
    image: xdaichain/ethstats-agent:latest
    links:
      - "node"
    depends_on:
      - "node"
    environment:
      NODE_ENV: production
      RPC_HOST: ${ETHSTATS_RPC_NODE}
      RPC_PORT: 8545
      LISTENING_PORT: 40101
      CONTACT_DETAILS: ${ETHSTATS_CONTACT}
      INSTANCE_NAME: ${ETHSTATS_ID}
      WS_SERVER: ${ETHSTATS_WS}
      WS_SECRET: ${ETHSTATS_KEY}
      VERBOSITY: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  node:
    init: true
    container_name: node
    image: ghcr.io/finachain/openethereum:main
    user: root
    command:
      --chain=finachain
      --port=40101
      --base-path=/root/data
      --min-gas-price="1100000000"
      --pruning=archive
      --max-peers="100"
      --jsonrpc-port="8545"
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=safe
      --fat-db="off"
      --tracing="off"
      --ws-port="8546"
      --ws-interface=all
      --ws-apis=safe
      --ws-origins=all
      --ws-hosts=all
      --logging="engine=info,miner=info,rpc=info"
    volumes:
      - ./node_data:/root/data
      - ./passwords:/root/password
      - ./keys:/root/data/keys/finachain
    network_mode: host
    restart: always