version: '3.7'
services:
  node:
    init: true
    container_name: node
    image: ghcr.io/finachain/openethereum:main
    user: root
    command:
      --chain=finachain
      --port=40101
      --nat="extip:$EXTERNAL_IP"      
      --node-key=$NODE_KEY
      --base-path=/root/data
      --pruning=archive
      --max-peers="100"
      --no-jsonrpc
      --fat-db="off"
      --tracing="off"
      --no-ws
      --author=$ACCOUNT
      --engine-signer=$ACCOUNT
      --unlock=$ACCOUNT
      --password="/root/password/$ACCOUNT"
      --force-sealing
      --logging="engine=info,miner=info,rpc=info"
    volumes:
      - ./node_data:/root/data
      - ./passwords:/root/password
    ports:
      - "40101:40101"
      - "40101:40101/udp"
    restart: always