version: '3.7'
services:
  blockscout:
    container_name: "blockscout"
    image: ghcr.io/finachain/blockscout:latest
    network_mode: host
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:@host.docker.internal:5432/blockscout?ssl=false"
      COIN: "FNA"
      NETWORK: "FinaChain"
      SUBNETWORK: "Main"
      LOGO: "/images/finachain_logo.svg"
      BLOCKSCOUT_HOST: "finascan.io"
      COINGECKO_COIN_ID: "fina"
      VALIDATORS_CONTRACT: "0x702BbdDE73d4fA0BC0E506ef69A65950586CaFD6"
      TOKEN_BRIDGE_CONTRACT: ""
      HIDE_BLOCK_MINER: "false"
      DISPLAY_TOKEN_ICONS: "true"
      BLOCKSCOUT_PROTOCOL: "https"
      ETHEREUM_JSONRPC_VARIANT: "parity"
      ETHEREUM_JSONRPC_HTTP_URL: "https://rpc-tracing.finachain.com"
      ETHEREUM_JSONRPC_TRACE_URL: "https://rpc-tracing.finachain.com"
      ETHEREUM_JSONRPC_WS_URL: "ws://ws-rpc-tracing.finachain.com"
      SECRET_KEY_BASE: "RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5"
      PORT: "4000"
      MIX_ENV: "prod"
      CHAIN_ID: "40101"
      CHAIN_SPEC_PATH: "https://raw.githubusercontent.com/finachain/finachain/main/specs/finachain.json"
      LINK_TO_OTHER_EXPLORER: "false"
      SHOW_PRICE_CHART: "false"
      SHOW_TXS_CHART: "true"
      ENABLE_TXS_STATS: "true"
      ENABLE_POS_STAKING_IN_MENU: "true"
      GAS_PRICE: "1"
      POS_STAKING_CONTRACT: "0xD4eF2E655412aA54BDCdE9Bf1d07860FDFb73c54"
      ECTO_USE_SSL: "false"
    command: "mix do ecto.create, ecto.migrate, phx.server"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:13.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data