version: '3.7'
services:
  blockscout:
    image: ghcr.io/finachain/blockscout:latest
    network_mode: host
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:@host.docker.internal:5432/blockscout?ssl=false"
      COIN: "FNA"
      NETWORK: "FinaChain"
      SUBNETWORK: "Main"
      LOGO: "/images/finachain_logo.svg"
      BLOCKSCOUT_HOST: "finascan.io"
      COINGECKO_COIN_ID: "fina"
      VALIDATORS_CONTRACT: "0x636278bAd2D76AAC5E9bAcfd185687c8901063E9"
      TOKEN_BRIDGE_CONTRACT: "0x8B95D92bea3e67796A105c19c524Ee8ef87Bd537"
      HIDE_BLOCK_MINER: "false"
      DISPLAY_TOKEN_ICONS: "true"
      BLOCKSCOUT_PROTOCOL: "https"
      ETHEREUM_JSONRPC_VARIANT: "parity"
      ETHEREUM_JSONRPC_HTTP_URL: "https://rpc.finachain.com"
      ETHEREUM_JSONRPC_TRACE_URL: "https://rpc.finachain.com"
      SECRET_KEY_BASE: "RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5"
      PORT: "4000"
      MIX_ENV: "prod"
      CHAIN_ID: "40101"
      CHAIN_SPEC_PATH: "https://raw.githubusercontent.com/finachain/finachain/main/specs/finachain.json"
      LINK_TO_OTHER_EXPLORER: "false"
      SHOW_PRICE_CHART: "false"
      SHOW_TXS_CHART: "true"
      ENABLE_TXS_STATS: "true"
      ENABLE_POS_STAKING_IN_MENU: "true"
      GAS_PRICE: "1"
      POS_STAKING_CONTRACT: "0xF69e9147d88De50c4Bd42F9b41Cbce00841Cc2Dd"
      ECTO_USE_SSL: "false"
    command: "mix do ecto.create, ecto.migrate, phx.server"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:13.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data