version: '3.7'
services:
  node:
    init: true
    container_name: node
    image: ghcr.io/finachain/openethereum:main
    user: root
    command:
      --chain=finachain
      --base-path=/root/data
      --pruning=archive
      --max-peers="100"
      --jsonrpc-port="8545"
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --fat-db="on"
      --tracing="on"
      --ws-port="8546"
      --ws-interface all
      --ws-apis=all
      --ws-origins all
      --ws-hosts all
      --logging="engine=trace,miner=trace,rpc=info"
    volumes:
      - ./node_data:/root/data
      - ./passwords:/root/password
      - ./keys:/root/data/keys/finachain
    ports:
      - "8546:8546"
      - "8545:8545"
      - "40101:40101"
      - "40101:40101/udp"
    restart: always