version: '3.7'
services:
  node:
    init: true
    container_name: node
    image: ghcr.io/finachain/finachain:main
    user: root
    volumes:
      - ./node_data/db:/nethermind/nethermind_db/
      - ./node_data/keystore/:/nethermind/keystore
    environment:
      NETHERMIND_CONFIG: "finachain_archive"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SECRET: ${ETHSTATS_KEY}
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://stats.finachain.com/api"
      NETHERMIND_ETHSTATSCONFIG_NAME: ${ETHSTATS_ID}
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES: "eth,subscribe,trace,txpool,web3,proof,net,parity,health"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: "0.0.0.0"
      NETHERMIND_HEALTHCHECKSCONFIG_ENABLED: "true"
      NETHERMIND_HEALTHCHECKSCONFIG_MAXINTERVALWITHOUTPROCESSEDBLOCK: 20
      NETHERMIND_METRICSCONFIG_ENABLED: "true"
      NETHERMIND_METRICSCONFIG_NODENAME: $NAME
    network_mode: host
    restart: always


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - "9090:9090"
    networks:
      - metrics

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - metrics
    volumes:
      - ./grafana/:/etc/grafana/provisioning/

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    volumes:
      - "./seq/:/data"
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"

networks:
  metrics:
    driver: bridge

volumes:
  prometheus_data: {}