version: '3.7'
services:
  swapapi:
    image: ghcr.io/finachain/finaswap:main
    environment:
      SwapConfiguration__ContractAddress: ${SWAPCONFIGURATION_CONTRACTADDRESS}
      SwapConfiguration__RpcEndpoint: ${SWAPCONFIGURATION_RPCENDPOINT}
      SwapConfiguration__PrivateKey: ${SWAPCONFIGURATION_PRIVATEKEY}
      SwapConfiguration__ChainId: ${SWAPCONFIGURATION_CHAINID}
      SwapConfiguration__DecimalPlaces: ${SWAPCONFIGURATION_DECIMALPLACES}
      SwapConfiguration__Prefix: ${SWAPCONFIGURATION_PREFIX}
      SwapConfiguration__EtherAmountWei: ${SWAPCONFIGURATION_ETHERAMOUNTWEI}
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Production"

    network_mode: host
    restart: always