version: '3.7'
services:
  validator:
    init: true
    container_name: validator
    image: ghcr.io/finachain/finachain:main
    user: root
    volumes:
      - ../../passwords/:/nethermind/passwords
      - ../../db/:/nethermind/nethermind_db
      - ../../keystore/:/nethermind/keystore
      - ../../logs/:/nethermind/logs/
      - ./NLog.config:/nethermind/NLog.config
    environment:
      NETHERMIND_CONFIG: "finachain_archive_validator"
      NETHERMIND_AURACONFIG_FORCESEALING: "true"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SECRET: ${ETHSTATS_KEY}
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://stats.finachain.com/api"
      NETHERMIND_ETHSTATSCONFIG_NAME: ${ETHSTATS_ID}
      NETHERMIND_INITCONFIG_ISMINING: "true"
      NETHERMIND_MININGCONFIG_ENABLED: "true"
      NETHERMIND_INITCONFIG_STORERECEIPTS: "false"
      NETHERMIND_MININGCONFIG_MINGASPRICE: "1000000000"
      NETHERMIND_MININGCONFIG_TARGETBLOCKGASLIMIT: "20000000"
      NETHERMIND_PRUNINGCONFIG_ENABLED: "false"
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_SYNCCONFIG_FASTBLOCKS: "true"
      NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC: "false"
      NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC: "false"
      NETHERMIND_KEYSTORECONFIG_BLOCKAUTHORACCOUNT: $ACCOUNT
      NETHERMIND_KEYSTORECONFIG_UNLOCKACCOUNTS: "$ACCOUNT"
      NETHERMIND_KEYSTORECONFIG_PASSWORDFILES: /nethermind/passwords/$ACCOUNT
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
    ports:
      - "40101:40101"
      - "40101:40101/udp"
    restart: always