name: Compile DAO Manifesto

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: manifesto/manifesto.tex
