name: Update configs

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-block:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Update block for Sparta
      run: "./scripts/update_blocks.sh sparta"
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Update blocks'

